# Generated by Django 2.2.1 on 2020-07-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Example1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='example1',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='example1',
            name='age',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='example1',
            name='curp',
            field=models.CharField(default='', max_length=16),
        ),
    ]
